#!/usr/bin/env python3
"""Regenerate MANIFEST.md from the actual tree.

MANIFEST.md is the repo's own index. It was stale by seven files when this effort
started, while claiming "200 files total", and a stale index is worse than none: a
reader trusts it and concludes a file does not exist.

Enumeration is `git ls-files --cached --others --exclude-standard`, so it sees tracked
files and new untracked ones, and it cannot name a file that does not exist. Paths are
written repo-relative and in full, so `scripts/verify.py` can compare them exactly
rather than guessing from a basename.

Run:  venv/bin/python scripts/build_manifest.py
"""
import os
import subprocess
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "MANIFEST.md")

# Section order and the one-line purpose each carries. A directory with no entry here
# is still listed, under "Other", rather than silently dropped: a file that exists and
# is not in the manifest is the exact failure this file exists to prevent.
SECTIONS = [
    ("", "Repo root"),
    ("01_START_HERE", "01_START_HERE — orientation"),
    ("02_findings", "02_findings — the current verdicts"),
    ("03_research", "03_research — literature and repo sweeps"),
    ("04_live_system", "04_live_system — the dashboard and its engines"),
    ("04_live_system/panels", "04_live_system/panels — panel functions, one dict each"),
    ("04_live_system/templates", "04_live_system/templates — Jinja templates"),
    ("04_live_system/templates/panels", "04_live_system/templates/panels — one per panel"),
    ("04_live_system/static", "04_live_system/static — stylesheet and refresh script"),
    ("05_studies", "05_studies — backtest and hunt harnesses"),
    ("05_studies/scripts", "05_studies/scripts — research harnesses"),
    ("06_data_guide", "06_data_guide — the data inventory"),
    ("07_superseded", "07_superseded — retired documents, not instructions"),
    ("docs", "docs — plan, audit, verdict log, UI spec"),
    ("idt", "idt — the shared package and CLI"),
    ("scripts", "scripts — repo tooling"),
    ("test", "test — the offline suite"),
    ("test/fixtures", "test/fixtures — frozen snapshots"),
    (".github/workflows", ".github/workflows — CI"),
]


def tracked():
    out = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
        cwd=ROOT, capture_output=True, text=True, check=True).stdout.split("\n")
    return sorted(p for p in out if p and os.path.isfile(os.path.join(ROOT, p)))


def measure(rel):
    p = os.path.join(ROOT, rel)
    size = os.path.getsize(p)
    try:
        with open(p, "rb") as fh:
            lines = sum(1 for _ in fh)
    except OSError:
        lines = 0
    human = f"{size} B" if size < 1024 else (
        f"{size / 1024:.0f} KB" if size < 1024 * 1024 else f"{size / 1024 / 1024:.1f} MB")
    return lines, human


def main():
    files = tracked()
    by_dir = defaultdict(list)
    for rel in files:
        by_dir[os.path.dirname(rel)].append(rel)

    known = {d for d, _ in SECTIONS}
    order = list(SECTIONS) + [(d, f"{d} — other") for d in sorted(by_dir) if d not in known]

    total_lines = 0
    body = []
    for d, title in order:
        entries = by_dir.get(d)
        if not entries:
            continue
        rows, sect_lines = [], 0
        for rel in entries:
            n, human = measure(rel)
            sect_lines += n
            rows.append(f"| `{rel}` | {n:,} | {human} |")
        total_lines += sect_lines
        body.append(f"\n## {title}\n\n*{len(entries)} files, {sect_lines:,} lines*\n")
        body.append("| file | lines | size |\n|---|---:|---:|")
        body.extend(rows)

    head = f"""# Manifest

Generated by `scripts/build_manifest.py` from `git ls-files --cached --others
--exclude-standard`, so it cannot name a file that does not exist or miss one that does.
Paths are repo-relative and complete; `scripts/verify.py` compares this list against the
tree on every run and fails if they disagree.

**What is deliberately not here.** The 16 GB of market data (see
[06_data_guide/DATA.md](06_data_guide/DATA.md)), the virtualenv, `__pycache__`, build
metadata and `.env`. All are gitignored, and none is reconstructible from this repo.

**{len(files):,} files, {total_lines:,} lines.**
"""
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(head + "\n".join(body) + "\n")
    print(f"MANIFEST.md: {len(files):,} files, {total_lines:,} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
